
redis:
  image: redis:latest
  links:
    - weba
    - webb
    - webc

weba:
    build: src
    ports:
      - 5000
    links:
      - redis

webb:
    build: src
    ports:
      - 5000
    links:
      - redis

webc:
    build: src
    ports:
      - 5000
    links:
      - redis

haproxy:
  image: haproxy:1.5
  volumes:
   - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
  links:
   - weba
   - webb
   - webc
  ports:
   - "80:80"
   - "70:70"

  expose:
   - "80"
   - "70"
